apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  labels:
    app: notes-app
spec:
  selector:
    app: notes-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000